filepath: ""
namespace: jx-vault
repositories:
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jx3
  url: https://charts.jenkins.io
releases:
- chart: banzaicloud-stable/vault-operator
  name: vault-operator
  version: 1.18.0
  forceNamespace: ""
  skipDeps: null
- chart: jxgh/vault-instance
  name: vault-instance
  version: 1.0.27
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}
